version: '3.8'
services:
  biab-mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: ds
      MYSQL_USER: biab
      MYSQL_PASSWORD: Sairam@123
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mynetwork

volumes:
  mysql-data:

networks:
  mynetwork:
